<?php

/**
 * @file
 * Main module file for Azure Entity Moderation Webform integration.
 */

namespace Drupal\azure_entity_moderation_webform;

use WebformElementViews\WebformAzureEntityModerationViews;

/**
 * @file
 * Main module file.
 */

// Replace the deprecated function with the recommended one.
\Drupal::service('module_handler')->loadInclude('webform', 'inc', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function azure_entity_moderation_webform_theme() {
  $info = [
    'webform_azure_entity_moderation' => [
      'render element' => 'element',
    ],
  ];

  return $info;
}

/**
 * Prepares variables for azure_entity_moderation_webform template.
 *
 * Webform_azure_entity_moderation template:
 * webform-azure-entity-moderation.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_azure_entity_moderation(array &$variables) {
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}

/**
 * Implements hook_webform_element_info_alter().
 */
function azure_entity_moderation_webform_webform_element_info_alter(array &$elements) {
  foreach ($elements as $k => $v) {
    if ($k == 'azure_entity_moderation') {
      $views_handler = WebformAzureEntityModerationViews::class;
      $elements[$k]['webform_views_handler'] = $views_handler;
    }
  }
}
